//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delivr.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notre histoire a débuté avec un groupe de 4 amis, à la fin 2003. Ensemble, ils ont couvés l&apos;idée qui allait plus tard devenir &lt;strong&gt;Delivr&lt;/strong&gt;..
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une &lt;em&gt;véritable révolution&lt;/em&gt; pour l&apos;industrie de la restauration. &lt;strong&gt;Delivr&lt;/strong&gt; amène un vent de fraîcheur aux communautés partout à travers l&apos;Amérique du Nord..
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous visons à fournir des services de livraison et, par conséquent, une facilité d&apos;accès à n&apos;importe quel restaurant dans un rayon de 40 kilomètres de votre domicile..
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de nous.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorez notre sélection.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez parmi une vaste sélection de restaurants.
        /// </summary>
        public static string Browse2 {
            get {
                return ResourceManager.GetString("Browse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renseignements commerciaux.
        /// </summary>
        public static string BusinessInquiries {
            get {
                return ResourceManager.GetString("BusinessInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactez-nous !.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Des repas &lt;strong&gt;délicieux&lt;/strong&gt;, livrés jusqu&apos;au pas de votre&lt;strong&gt;porte&lt;/strong&gt;.&lt;/p&gt;.
        /// </summary>
        public static string DeliveryPromotion {
            get {
                return ResourceManager.GetString("DeliveryPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Toutes les commandes seront livrées &lt;br /&gt; en dedans d&apos;&lt;strong&gt;une heure&lt;/strong&gt;,&lt;br /&gt; Garanti!&lt;/p&gt;
        ///&lt;p&gt;Si non, &lt;strong&gt;nous payons&lt;/strong&gt; votre repas!&lt;/p&gt;.
        /// </summary>
        public static string DeliveryTimeGuarantee {
            get {
                return ResourceManager.GetString("DeliveryTimeGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon appétit!.
        /// </summary>
        public static string Enjoy {
            get {
                return ResourceManager.GetString("Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous espérons que vous apprécierez.
        /// </summary>
        public static string Enjoy2 {
            get {
                return ResourceManager.GetString("Enjoy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cela fonctionne :.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joignez notre communauté grandissante&lt;br /&gt;et apprenez à &lt;strong&gt;relaxer&lt;/strong&gt;.&lt;br /&gt;Inscrivez-vous &lt;strong&gt;maintenant&lt;/strong&gt;!.
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notre mission.
        /// </summary>
        public static string OurMission {
            get {
                return ResourceManager.GetString("OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payez.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ligne ou à la porte.
        /// </summary>
        public static string Pay2 {
            get {
                return ResourceManager.GetString("Pay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À la porte.
        /// </summary>
        public static string PaymentMethodDoor {
            get {
                return ResourceManager.GetString("PaymentMethodDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À la porte, vous pourrez payer avec Visa, MasterCard, Interact ainsi que la bonne vieille monnaie..
        /// </summary>
        public static string PaymentMethodDoorDetails {
            get {
                return ResourceManager.GetString("PaymentMethodDoorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ligne.
        /// </summary>
        public static string PaymentMethodOnline {
            get {
                return ResourceManager.GetString("PaymentMethodOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous acceptions Visa, MasterCard, Paypal et Interact, en plus de de votre devise électronique préférée..
        /// </summary>
        public static string PaymentMethodOnlineDetails {
            get {
                return ResourceManager.GetString("PaymentMethodOnlineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méthodes de paiement.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez-vous un repas.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou pourquoi pas 2 !.
        /// </summary>
        public static string Pick2 {
            get {
                return ResourceManager.GetString("Pick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
    }
}
