//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delivr.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse our selection.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from a huge selection of restaurants.
        /// </summary>
        public static string Browse2 {
            get {
                return ResourceManager.GetString("Browse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Delicious &lt;strong&gt;food&lt;/strong&gt;, delivered right to your &lt;strong&gt;doorstep&lt;/strong&gt;.&lt;/p&gt;.
        /// </summary>
        public static string DeliveryPromotion {
            get {
                return ResourceManager.GetString("DeliveryPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;All orders are delivered &lt;br /&gt; in &lt;strong&gt;under an hour&lt;/strong&gt;,&lt;br /&gt; Guaranteed!&lt;/p&gt;
        ///&lt;p&gt;If not, you get your meal at &lt;strong&gt;no charge&lt;/strong&gt;!&lt;/p&gt;.
        /// </summary>
        public static string DeliveryTimeGuarantee {
            get {
                return ResourceManager.GetString("DeliveryTimeGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon appétit!.
        /// </summary>
        public static string Enjoy {
            get {
                return ResourceManager.GetString("Enjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope you enjoy.
        /// </summary>
        public static string Enjoy2 {
            get {
                return ResourceManager.GetString("Enjoy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works:.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our growing community &lt;br /&gt; and learn to &lt;strong&gt;stop worrying&lt;/strong&gt;.&lt;br /&gt;Sign up &lt;strong&gt;now&lt;/strong&gt;!.
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either online or at the door.
        /// </summary>
        public static string Pay2 {
            get {
                return ResourceManager.GetString("Pay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the door.
        /// </summary>
        public static string PaymentMethodDoor {
            get {
                return ResourceManager.GetString("PaymentMethodDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the door, you&apos;ll be able to use either Visa or MasterCard if you&apos;re paying credit, Interact or good old cash..
        /// </summary>
        public static string PaymentMethodDoorDetails {
            get {
                return ResourceManager.GetString("PaymentMethodDoorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string PaymentMethodOnline {
            get {
                return ResourceManager.GetString("PaymentMethodOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We accept Visa, MasterCard, Paypal and Interact as well as any of your favorite crypto currencies..
        /// </summary>
        public static string PaymentMethodOnlineDetails {
            get {
                return ResourceManager.GetString("PaymentMethodOnlineDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a meal.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or more!.
        /// </summary>
        public static string Pick2 {
            get {
                return ResourceManager.GetString("Pick2", resourceCulture);
            }
        }
    }
}
