//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Commande {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commande() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delivr.Resources.Commande.Commande", typeof(Commande).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminer la préparation.
        /// </summary>
        public static string FinishPreparation {
            get {
                return ResourceManager.GetString("FinishPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandes en cours.
        /// </summary>
        public static string PendingOrders {
            get {
                return ResourceManager.GetString("PendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préparer cette commande.
        /// </summary>
        public static string PrepareThisOrder {
            get {
                return ResourceManager.GetString("PrepareThisOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livrée.
        /// </summary>
        public static string StatusDelivered {
            get {
                return ResourceManager.GetString("StatusDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En livraison.
        /// </summary>
        public static string StatusInDelivery {
            get {
                return ResourceManager.GetString("StatusInDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En préparation.
        /// </summary>
        public static string StatusInPreparation {
            get {
                return ResourceManager.GetString("StatusInPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En traitement.
        /// </summary>
        public static string StatusProcessing {
            get {
                return ResourceManager.GetString("StatusProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prête.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total :.
        /// </summary>
        public static string TotalWithColon {
            get {
                return ResourceManager.GetString("TotalWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éléments.
        /// </summary>
        public static string UnitsLowercase {
            get {
                return ResourceManager.GetString("UnitsLowercase", resourceCulture);
            }
        }
    }
}
